### ISSUE TITLE
Update docker image with latest Alpine security fixes

### ISSUE THREAD

**Issue by iarenaza** [immontilla/docker-mitreid-oidc-server#1]
Docker maintainers have published new Alpine images fixing an important security bug in apk-tools (see 
https://github.com/docker-library/official-images/pull/4834).

Your image available in Docker Hub is built using a vulnerable version of Alpine, so please create a new image using the latest fixed version of Alpine images.

**Comment by immontilla** [comment]
Thanks for pointing that out and please excuse this delayed response.
I have forced a build today so now is fixed.
Thanks again.
